# Generated by Django 4.2.7 on 2023-11-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.CharField(max_length=30, null=True)),
                ('auto_features', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
